@startuml
autonumber
skinparam MaxMessageSize 150
title Client Credentials Flow secured API Gateway endpoint



participant "M2M App\n " as m2m
participant "Cognito Token Endpoint \n/oauth2/token" as token
participant "API Gateway Endpoint \nexecute-api.{region}.amazonaws.com" as api
participant "Cognito User Pool Authorizer\n " as auth

m2m -> token: Authenticate with Client ID & Client Secret to /oauth2/token
token -> token: Validate Client ID & Client Secret
token -> m2m: Return Access token
m2m -> api: Send HTTP request to API with Access Token in the Authroization Header
api -> auth: 
auth -> auth: Check if Access Token is valid & check if OAuth scope allows the requested API method
auth -> api: Pass/Fail
api -> m2m: API Execution response


@enduml